"""dernier acces

Revision ID: 1334ba2bd729
Revises: 5f59918fb6f2
Create Date: 2023-09-13 13:54:07.410114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1334ba2bd729'
down_revision = '5f59918fb6f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.alter_column('corps',
               existing_type=sa.TEXT(length=140),
               type_=sa.String(length=140),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_publication_horodatage'), ['horodatage'], unique=False)

    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dernier_acces', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('dernier_acces')

    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_horodatage'))
        batch_op.alter_column('corps',
               existing_type=sa.String(length=140),
               type_=sa.TEXT(length=140),
               existing_nullable=True)

    # ### end Alembic commands ###
