"""users table

Revision ID: 2e45cfea6b1c
Revises: ef853778ce93
Create Date: 2023-12-01 17:02:06.998812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e45cfea6b1c'
down_revision = 'ef853778ce93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ImagePub', sa.Text(length=131072), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('ImagePub')

    # ### end Alembic commands ###
