"""empty message

Revision ID: 5f59918fb6f2
Revises: 44a51ea57fb7
Create Date: 2023-08-30 15:46:30.843615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f59918fb6f2'
down_revision = '44a51ea57fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('a_propos_de_moi', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('a_propos_de_moi')

    # ### end Alembic commands ###
